{% set name = "river" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/river-{{ version }}.tar.gz
  sha256: 9d068b7a9db32302fbd581af81315681dfe61774a5d777fb3d5982d3c3061340

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - python
    - setuptools-rust
    - numpy
    - cython
    - pip
  run:
    - python
    - scipy >=1.5
    - pandas >=1.3
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - river
    - river.anomaly
    - river.base
    - river.cluster
    - river.compat
    - river.compose
    - river.datasets
    - river.datasets.synth
    - river.drift
    - river.dummy
    - river.ensemble
    - river.evaluate
    - river.facto
    - river.feature_extraction
    - river.feature_selection
    - river.imblearn
    - river.linear_model
    - river.metrics
    - river.metrics.cluster
    - river.multiclass
    - river.multioutput
    - river.naive_bayes
    - river.neighbors
    - river.optim
    - river.optim.initializers
    - river.optim.losses
    - river.optim.schedulers
    - river.preprocessing
    - river.proba
    - river.reco
    - river.stats
    - river.stream
    - river.time_series
    - river.optim
    - river.optim.initializers
    - river.optim.losses
    - river.optim.schedulers
    - river.preprocessing
    - river.proba
    - river.reco
    - river.stats
    - river.stream
    - river.time_series
    - river.tree
    - river.tree.splitter
    - river.utils
    - river.utils.math
    - river.utils.pretty
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/online-ml/river
  summary: Online machine learning in Python
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - bubblyorca
    - synapticarbors
